-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 19:40:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agg1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agg1` (
  `Themes` VARCHAR(45) NOT NULL,
  `MentionTimeDate` DATETIME NULL,
  `count` INT NULL,
  `AvgTone` DECIMAL(3) NULL,
  UNIQUE INDEX `Themes_UNIQUE` (`Themes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agg2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agg2` (
  `Theme` VARCHAR(45) NOT NULL,
  `MentionTimeDate` DATETIME NULL,
  `count` INT NULL,
  `AvgTone` DECIMAL(3) NULL,
  `MentionSourceName` VARCHAR(45) NULL,
  UNIQUE INDEX `Theme_UNIQUE` (`Theme` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
